# Generated by Django 3.2.10 on 2021-12-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', '초안'), ('P', '공개')], db_index=True, default='D', max_length=1),
        ),
    ]
